//list of words to guess.
exports.newWord = {
  wordList:["THOR", 
  "SPIDERMAN", 
  "LOKI", 
  "THANOS", 
  "GROOT", 
  "ULTRON", 
  "STORM", 
  "ELEKTRA", 
  "ROGUE", 
  "MAGNETO", 
  "DORMAMMU", 
  "CYCLOPSE", 
  "WOLVERINE", 
  "DEADPOOL", 
  "HAWKEYE", 
  "DAREDEVIL", 
  "BLADE", 
  "APOCALYPSE", 
  "GAMORA", 
  "ROCKET RACOON", 
  "HULK", 
  "JUGGERNAUT", 
  "CABLE", 
  "BEAST",
  "VENOM",
  "IRON MAN"],
  hangman: ["\n\n\n\n\n\n\n-------------", "\n |\n |\n |\n |\n |\n |\n |\n-------------", "____________\n |         |\n |\n |\n |\n |\n |\n-------------","____________\n |         |\n |         O\n |\n |\n |\n |\n |\n-------------","____________\n |         |\n |         O\n |         |\n |         |\n |\n |\n |\n-------------","____________\n |         |\n |         O\n |         |\n |         |\n |        ---\n |\n |\n-------------", "____________\n |         |\n |         O\n |       __|\n |         |\n |        ---\n |\n |\n-------------", "____________\n |         |\n |         O\n |       __|__\n |         |\n |        ---\n |\n |\n-------------", "____________\n |         |\n |         O\n |       __|__\n |         |\n |        ---\n |        |\n |\n-------------","____________\n |         |\n |         O\n |       __|__\n |         |\n |        ---\n |        | |\n |\n-------------"]
};